services:
  traffic-monitor:
    image: npcdw/traffic-monitor:latest
    container_name: traffic-monitor
    network_mode: "host"
    # 如果需要在流量到达限制后，执行宿主机命令，需要放开这两个
    # pid: host
    # privileged: true
    volumes:
      - "${PWD}/data/:/traffic-monitor/data"
      - "${PWD}/config/:/traffic-monitor/config"
    environment:
      TZ : 'Asia/Shanghai'
      LANG: 'C.UTF-8'
      LC_ALL: 'C.UTF-8'